name: test-mdl-{name}
download: git clone https://github.com/snapcraft-docs/mdl
createDir: |
  cd mdl
  $EDITOR snapcraft.yaml
metadata: |
  name: mdl
  version: "0.5.0"
  summary: Markdown lint tool
  description: |
    Style checker/lint tool for markdown files.
explain:
  metadata:
    - text: The name must be unique in the Snap Store. Valid snap names consist of lower-case alphanumeric characters and hyphens. They cannot be all numbers. They also cannot start or end with a hyphen.
    - code: |
        name: mdl
    - warning: |
        <span class="p-notification__status">Snap names are globally unique.</span> You should change any instance of <code>mdl</code> to <code>test-mdl-{name}</code> (where <code>{name}</code> is your name) before continuing to avoid conflicting with the official mdl snap.
    - text: Versions carry no semantic meaning in snaps. Use text that best identifies that release, it won't be used to compare against the preceding or following one.
    - code: |
        version: "0.5.0"
    - text: The summary can not exceed 79 characters. You can use a pipe ‘|’ in the description key to declare a multi-line description.
    - code: |
        description: |
  security:
    - text: The next section describes the level of confinement applied to your app.
    - code: |
        confinement: devmode
    - text: Snaps are containerised to ensure more predictable application behaviour and greater security.
    - text: It’s best to start a snap with the confinement in warning mode, rather than strictly applied. This is indicated through the <code>devmode</code> keyword.
    - text: Once an app is working well in devmode, you can review confinement violations, add appropriate interfaces, and switch to strict confinement.
  base:
    - text: In general, snaps cannot see the root filesystem on end user systems. This prevents conflict with other applications and increases security. However, applications still need some location to act as the root filesystem. They would also benefit from common libraries (e.g. libc) being in this root filesystem rather than bundled into each application.
    - text: The base keyword specifies a special kind of snap that provides a minimal set of libraries common to most applications. It will be mounted as the root filesystem for your application.
    - code: |
        base: core18
    - text: The <code>core18</code> base is recommended.
  parts:
    - text: |
        Parts define what sources are needed to assemble your app. Parts can be anything: programs, libraries, or other needed assets. The <code>gem</code> package manager will install the <code>rake</code> and <code>bundler</code> programs to satisfy the dependencies.
    - code: |
        parts:
          mdl:
            source: .
            plugin: ruby
            gems:
              - rake
              - bundler
            override-build: |
              snapcraftctl build
              rake install
            build-packages:
              - git
    - text: |
        The <code>override-build</code> keyword changes the behavior of the plugin as it builds the part. Here, the part will be made with <code>rake</code>.
    - text: |
        The <code>build-packages</code> section lists the dependencies that will be used by snapcraft to build the parts.
  apps:
    - text: Apps are the commands you want to expose to users and any background services your application provides.
    - code: |
        apps:
          mdl:
            command: bin/mdl
    - warning: |
        <span class="p-notification__status"></span>As before, remember to change this instance of <code>mdl</code> to <code>test-mdl-{name}</code> (where <code>{name}</code> is your name) before continuing to avoid conflicting with the official mdl snap.
    - text: The <code>command</code> specifies the path to the binary to be run. This is resolved relative to the root of your snap contents and automatically searches in the usr/sbin, usr/bin, sbin, and bin subdirectories of your snap.
    - text: If your command name matches the snap name, users will be able run the command directly.
