name: test-geekbench4-{name}
download: git clone https://github.com/snapcraft-docs/geekbench4
createDir: |
  cd geekbench4
  $EDITOR snapcraft.yaml
metadata: |
  name: geekbench4
  version: 4.2.0
  summary: Cross-Platform Benchmark
  description: |
    Geekbench 4 measures your system's power and tells
    you whether your computer is ready to roar. How
    strong is your mobile device or desktop computer?
    How will it perform when push comes to crunch?
    These are the questions that Geekbench can answer.
explain:
  metadata:
    - text: The name must be unique in the Snap Store. Valid snap names consist of lower-case alphanumeric characters and hyphens. They cannot be all numbers. They also cannot start or end with a hyphen.
    - code: |
        name: geekbench4
    - warning: |
        <span class="p-notification__status">Snap names are globally unique.</span> You should change any instance of <code>geekbench4</code> to <code>test-geekbench4-{name}</code> (where <code>{name}</code> is your name) before continuing to avoid conflicting with the official geekbench4 snap.
    - text: Versions carry no semantic meaning in snaps. You can move end user installs from 4.1.0 to 4.2.0, and back to 4.1.0 in the event of a premature release.
    - code: |
        version: 4.2.0
    - text: The summary can not exceed 79 characters. You can use a pipe ‘|’ in the description key to declare a multi-line description.
    - code: |
        description: |
  security:
    - text: The next section describes the level of confinement applied to your app.
    - code: |
        confinement: devmode
    - text: Snaps are containerised to ensure more predictable application behaviour and greater security.
    - text: It’s best to start a snap with the confinement in warning mode, rather than strictly applied. This is indicated through the <code>devmode</code> keyword.
    - text: Once an app is working well in devmode, you can review confinement violations, add appropriate interfaces, and switch to strict confinement.
  base:
    - text: In general, snaps cannot see the root filesystem on end user systems. This prevents conflict with other applications and increases security. However, applications still need some location to act as the root filesystem. They would also benefit from common libraries (e.g. libc) being in this root filesystem rather than bundled into each application.
    - text: The base keyword specifies a special kind of snap that provides a minimal set of libraries common to most applications. It will be mounted as the root filesystem for your application.
    - code: |
        base: core18
    - text: The <code>core18</code> base is recommended.
  parts:
    - text: |
        Parts define what sources are needed to assemble your app. Parts can be anything: programs, libraries, or other needed assets.
    - code: |
        parts:
          geekbench4:
            plugin: dump
            source: http://cdn.geekbench.com/Geekbench-$SNAPCRAFT_PROJECT_VERSION-Linux.tar.gz
    - text: The <code>dump</code> plugin can extract tar, deb, rpm, and zip files.
    - text: The <code>source</code> keyword points to the location of the tar file. The <code>$SNAPCRAFT_PROJECT_VERSION</code> variable is replaced with '4.2.0' from the snapcraft.yaml <code>version</code>, specified earlier.
  apps:
    - text: Apps are the commands you want to expose to users and any background services your application provides.
    - code: |
        apps:
          test-geekbench4-{name}:
            command: geekbench4
    - warning: |
        <span class="p-notification__status"></span>As before, remember to change this instance of <code>geekbench4</code> to <code>test-geekbench4-{name}</code> (where <code>{name}</code> is your name) before continuing to avoid conflicting with the official geekbench4 snap.
    - text: The <code>command</code> specifies the path to the binary to be run. This is resolved relative to the root of your snap contents and automatically searches in the usr/sbin, usr/bin, sbin, and bin subdirectories of your snap.
    - text: If your command name matches the snap name, users will be able run the command directly.
